In [1]:
import numpy as np
import matplotlib.pyplot as plt  # To visualize
import pandas as pd  # To read data
from sklearn.linear_model import LinearRegression
import urllib
from urllib import request

In [4]:
fname = 'https://stepic.org/media/attachments/lesson/16462/boston_houses.csv'  # read file name from stdin
f = urllib.request.urlopen(fname)  # open file from URL
data = np.loadtxt(f, delimiter=',', skiprows=1)  # load data to work with

# here goes your solution
print(data)

[[2.4000e+01 6.3200e-03 1.8000e+01 ... 5.3800e-01 6.5750e+00 4.0900e+00]
 [2.1600e+01 2.7310e-02 0.0000e+00 ... 4.6900e-01 6.4210e+00 4.9671e+00]
 [3.4700e+01 2.7290e-02 0.0000e+00 ... 4.6900e-01 7.1850e+00 4.9671e+00]
 ...
 [2.3900e+01 6.0760e-02 0.0000e+00 ... 5.7300e-01 6.9760e+00 2.1675e+00]
 [2.2000e+01 1.0959e-01 0.0000e+00 ... 5.7300e-01 6.7940e+00 2.3889e+00]
 [1.1900e+01 4.7410e-02 0.0000e+00 ... 5.7300e-01 6.0300e+00 2.5050e+00]]


In [11]:
X = data[::,0].reshape(-1,1)

In [20]:
Y = data[::, 1::].reshape(-1, data.shape[1]-1)  # -1 means that calculate the dimension of rows, but have 1 column

In [27]:
linear_regressor = LinearRegression()  # create object for the class
reg = linear_regressor.fit(Y, X)  # perform linear regression
X_pred = reg.predict(Y)  # make predictions

In [34]:
reg.coef_

array([[ -0.2163955 ,   0.0737306 ,   4.41245058, -25.46844878,
          7.14320155,  -1.30108768]])

In [35]:
reg.intercept_

array([-3.65580429])

In [36]:
#теперь делаем через матрицы

In [81]:
X_matrix = X
Y_matrix = np.c_[np.ones(Y.shape[0]),Y]
print(Y_matrix)

[[1.0000e+00 6.3200e-03 1.8000e+01 ... 5.3800e-01 6.5750e+00 4.0900e+00]
 [1.0000e+00 2.7310e-02 0.0000e+00 ... 4.6900e-01 6.4210e+00 4.9671e+00]
 [1.0000e+00 2.7290e-02 0.0000e+00 ... 4.6900e-01 7.1850e+00 4.9671e+00]
 ...
 [1.0000e+00 6.0760e-02 0.0000e+00 ... 5.7300e-01 6.9760e+00 2.1675e+00]
 [1.0000e+00 1.0959e-01 0.0000e+00 ... 5.7300e-01 6.7940e+00 2.3889e+00]
 [1.0000e+00 4.7410e-02 0.0000e+00 ... 5.7300e-01 6.0300e+00 2.5050e+00]]


In [108]:
beta = np.linalg.inv((Y_matrix.T.dot(Y_matrix))).dot(Y_matrix.T).dot(X_matrix)

In [115]:
print(' '.join(map(str,map(float,beta))))

-3.6558042850732986 -0.21639550236912594 0.07373059817547865 4.412450576912806 -25.468448784090892 7.143201550746702 -1.301087677648551
